export type CarListItem = {
  id: string;
  brand: string;
  model: string;
  year: number;
  category: string;
  pricePerDay: number;
  transmission: "Automatic" | "Manual";
  fuelType: "Petrol" | "Diesel" | "Hybrid" | "Electric";
  seats: number;
  status: "Available" | "Occupied";
  imageUrl: string;
  location: string;
};

export const carCategories = [
  "Economy",
  "Sedan",
  "SUV",
  "Luxury",
  "Electric",
  "Hatchback",
] as const;

export const transmissions = ["Automatic", "Manual"] as const;
export const fuelTypes = ["Petrol", "Diesel", "Hybrid", "Electric"] as const;
export const seatFilters = ["2-4", "5", "7+"] as const;

export const mockCars: CarListItem[] = [
  {
    id: "toyota-corolla-2023",
    brand: "Toyota",
    model: "Corolla",
    year: 2023,
    category: "Sedan",
    pricePerDay: 55,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/toyota-corolla-2023.png",
    location: "Beirut",
  },
  {
    id: "nissan-xtrail-2022",
    brand: "Nissan",
    model: "X-Trail",
    year: 2022,
    category: "SUV",
    pricePerDay: 90,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/nissan-xtrail-2022.png",
    location: "Jounieh",
  },
  {
    id: "hyundai-tucson-2024",
    brand: "Hyundai",
    model: "Tucson",
    year: 2024,
    category: "SUV",
    pricePerDay: 120,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    status: "Occupied",
    imageUrl: "/cars/hyundai-tucson-2024.png",
    location: "Tripoli",
  },
  {
    id: "mercedes-c-class-2023",
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: 2023,
    category: "Luxury",
    pricePerDay: 150,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/mercedes-c-class-2023.png",
    location: "Beirut",
  },
  {
    id: "bmw-x5-2024",
    brand: "BMW",
    model: "X5",
    year: 2024,
    category: "Luxury",
    pricePerDay: 210,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    status: "Occupied",
    imageUrl: "/cars/bmw-x5-2024.png",
    location: "Zahle",
  },
  {
    id: "audi-q5-2023",
    brand: "Audi",
    model: "Q5",
    year: 2023,
    category: "Luxury",
    pricePerDay: 140,
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/audi-q5-2023.png",
    location: "Sidon",
  },
  {
    id: "tesla-model-y-2024",
    brand: "Tesla",
    model: "Model Y",
    year: 2024,
    category: "Electric",
    pricePerDay: 160,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/tesla-model-y-2024.png",
    location: "Beirut",
  },
  {
    id: "peugeot-208-2022",
    brand: "Peugeot",
    model: "208",
    year: 2022,
    category: "Hatchback",
    pricePerDay: 45,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/peugeot-208-2022.png",
    location: "Jounieh",
  },
  {
    id: "kia-cerato-2023",
    brand: "Kia",
    model: "Cerato",
    year: 2023,
    category: "Sedan",
    pricePerDay: 65,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/kia-cerato-2023.png",
    location: "Beirut",
  },
  {
    id: "mitsubishi-pajero-2023",
    brand: "Mitsubishi",
    model: "Pajero",
    year: 2023,
    category: "SUV",
    pricePerDay: 180,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 7,
    status: "Occupied",
    imageUrl: "/cars/mitsubishi-pajero-2023.png",
    location: "Byblos",
  },
  {
    id: "honda-civic-2022",
    brand: "Honda",
    model: "Civic",
    year: 2022,
    category: "Sedan",
    pricePerDay: 50,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/honda-civic-2022.png",
    location: "Beirut",
  },
  {
    id: "chevrolet-spark-2021",
    brand: "Chevrolet",
    model: "Spark",
    year: 2021,
    category: "Economy",
    pricePerDay: 38,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 4,
    status: "Available",
    imageUrl: "/cars/chevrolet-spark-2021.png",
    location: "Tripoli",
  },
  {
    id: "kia-picanto-2022",
    brand: "Kia",
    model: "Picanto",
    year: 2022,
    category: "Economy",
    pricePerDay: 35,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 4,
    status: "Available",
    imageUrl: "/cars/kia-picanto-2022.png",
    location: "Jounieh",
  },
  {
    id: "toyota-rav4-2024",
    brand: "Toyota",
    model: "RAV4",
    year: 2024,
    category: "SUV",
    pricePerDay: 110,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/toyota-rav4-2024.png",
    location: "Beirut",
  },
  {
    id: "range-rover-evoque-2023",
    brand: "Land Rover",
    model: "Range Rover Evoque",
    year: 2023,
    category: "Luxury",
    pricePerDay: 220,
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 5,
    status: "Occupied",
    imageUrl: "/cars/range-rover-evoque-2023.png",
    location: "Zahle",
  },
  {
    id: "porsche-panamera-2023",
    brand: "Porsche",
    model: "Panamera",
    year: 2023,
    category: "Luxury",
    pricePerDay: 250,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 4,
    status: "Available",
    imageUrl: "/cars/porsche-panamera-2023.png",
    location: "Beirut",
  },
  {
    id: "tesla-model-3-2023",
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    category: "Electric",
    pricePerDay: 130,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/tesla-model-3-2023.png",
    location: "Beirut",
  },
  {
    id: "nissan-leaf-2022",
    brand: "Nissan",
    model: "Leaf",
    year: 2022,
    category: "Electric",
    pricePerDay: 95,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/nissan-leaf-2022.png",
    location: "Sidon",
  },
  {
    id: "hyundai-accent-2021",
    brand: "Hyundai",
    model: "Accent",
    year: 2021,
    category: "Sedan",
    pricePerDay: 42,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/hyundai-accent-2021.png",
    location: "Jounieh",
  },
  {
    id: "volkswagen-golf-2022",
    brand: "Volkswagen",
    model: "Golf",
    year: 2022,
    category: "Hatchback",
    pricePerDay: 58,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Occupied",
    imageUrl: "/cars/volkswagen-golf-2022.png",
    location: "Tripoli",
  },
  {
    id: "jeep-wrangler-2023",
    brand: "Jeep",
    model: "Wrangler",
    year: 2023,
    category: "SUV",
    pricePerDay: 135,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/jeep-wrangler-2023.png",
    location: "Byblos",
  },
  {
    id: "ford-explorer-2022",
    brand: "Ford",
    model: "Explorer",
    year: 2022,
    category: "SUV",
    pricePerDay: 105,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 7,
    status: "Available",
    imageUrl: "/cars/ford-explorer-2022.png",
    location: "Beirut",
  },
  {
    id: "mazda-3-2023",
    brand: "Mazda",
    model: "3",
    year: 2023,
    category: "Sedan",
    pricePerDay: 60,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/mazda-3-2023.png",
    location: "Sidon",
  },
  {
    id: "suzuki-swift-2021",
    brand: "Suzuki",
    model: "Swift",
    year: 2021,
    category: "Hatchback",
    pricePerDay: 40,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 5,
    status: "Available",
    imageUrl: "/cars/suzuki-swift-2021.png",
    location: "Zahle",
  },
];