"use client";
import Link from "next/link";
import { Check, Eye, MoreHorizontal, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { AdminReservation } from "@/features/admin/reservations/admin-reservation.types";
import { ReservationStatusBadge } from "./reservation-status-badge";

const money = new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 });
const date = new Intl.DateTimeFormat("en-US", { month:"short", day:"numeric", year:"numeric" });
export function ReservationsTable({ reservations, onApprove, onReject }: { reservations:readonly AdminReservation[]; onApprove:(r:AdminReservation)=>void; onReject:(r:AdminReservation)=>void }) {
  return <div className="hidden overflow-hidden rounded-2xl rounded-b-none border border-b-0 bg-card shadow-xs md:block"><div className="overflow-x-auto"><table className="w-full min-w-275 text-left text-sm"><thead className="border-b bg-muted/40"><tr>{["Reference","Customer","Car","Rental period","Days","Total","Status","Actions"].map((h)=><th key={h} className={`px-5 py-4 font-medium text-muted-foreground ${h==="Total"||h==="Actions"?"text-right":""}`}>{h}</th>)}</tr></thead><tbody className="divide-y">{reservations.map((r)=><tr key={r.id} className="hover:bg-muted/30"><td className="px-5 py-4 font-semibold text-foreground">{r.reference}</td><td className="px-5 py-4"><p className="font-medium">{r.customer.fullName}</p><p className="text-xs text-muted-foreground">{r.customer.email}</p></td><td className="px-5 py-4"><p className="font-medium">{r.car.brand} {r.car.model}</p><p className="text-xs text-muted-foreground">{r.car.plateNumber}</p></td><td className="px-5 py-4 text-muted-foreground">{date.format(new Date(r.pickupDate))} – {date.format(new Date(r.returnDate))}</td><td className="px-5 py-4">{r.rentalDays}</td><td className="px-5 py-4 text-right font-semibold">{money.format(r.totalPrice)}</td><td className="px-5 py-4"><ReservationStatusBadge status={r.status}/></td><td className="sticky right-0 bg-card/95 px-5 py-4 text-right backdrop-blur"><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label={`Actions for ${r.reference}`} />}><MoreHorizontal/></DropdownMenuTrigger><DropdownMenuContent align="end"> <DropdownMenuItem render={<Link href={`/admin/reservations/${r.id}`} />}><Eye/>View details</DropdownMenuItem>{r.status==="pending"&&<><DropdownMenuItem onClick={()=>onApprove(r)}><Check/>Approve</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={()=>onReject(r)}><X/>Reject</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></td></tr>)}</tbody></table></div></div>;
}
